#!/bin/bash

log_info() {
  printf "\n\e[0;35m $1\e[0m\n\n"
}

start() {
    log_info "Starting HPC Utilities Cluster.."
    docker-compose up -d

    log_info "Coldfront URL: https://localhost:2443"
    log_info "OnDemand URL: https://localhost:3443"
    log_info "XDMoD URL: https://localhost:4443"
    log_info "Login to frontend: ssh -p 6222 hpcadmin@localhost"
}

stop() {
    log_info "Stopping HPC Utilities Cluster.."
    docker-compose stop
}

clean() {
    log_info "Stopping and removing HPC Utilities Cluster containers and volumes.."
    docker-compose stop && \
    docker-compose rm -f -v && \
    docker-compose down -v
}

case "$1" in
    'start')
        start
        ;;
    'stop')
        stop
        ;;
    'clean')
        clean
        ;;
    *)
        log_info "Usage: $0 { start | stop | clean }"
        exit 1
        ;;
esac
