#!/bin/bash

log_info() {
  printf "\n\e[0;35m $1\e[0m\n\n"
}

start() {
    log_info "Fetching latest HPC Toolset Images.."
    docker-compose pull

    log_info "Starting HPC Toolset Cluster.."
    docker-compose up -d --no-build

    log_info "Coldfront URL: https://localhost:2443"
    log_info "OnDemand URL: https://localhost:3443"
    log_info "XDMoD URL: https://localhost:4443"
    log_info "Login to frontend: ssh -p 6222 hpcadmin@localhost"
}

stop() {
    log_info "Stopping and removing HPC Toolset Cluster containers and volumes.."
    docker-compose stop && \
    docker-compose rm -f -v && \
    docker-compose down -v
}

cleanup() {
    log_info "Cleaning up HPC Toolset containers and images.."
    stop
    docker rmi $(docker images -f "reference=ubccr/hpcts*" -q)
}

case "$1" in
    'start')
        start
        ;;
    'stop')
        stop
        ;;
    'cleanup')
        cleanup
        ;;
    *)
        log_info "Usage: $0 { start | stop | cleanup}"
        exit 1
        ;;
esac
